# -*- coding: utf-8 -*-
# generated by wxGlade 0.6.3 on Wed Mar  5 15:24:35 2008

__revision__ = '$Id: $'

# Copyright (c) 2005-2008 Vasco Nunes, Piotr Ożarowski

# This program is free software; you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation; either version 2 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU Library General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program; if not, write to the Free Software
# 51 Franklin Street, Fifth Floor, Boston, MA  02110-1301, USA

# You may use and distribute this software under the terms of the
# GNU General Public License, version 2 or later

import wx

# begin wxGlade: dependencies
# end wxGlade

# begin wxGlade: extracode

# end wxGlade

class AddFrame(wx.Frame):
    def __init__(self, *args, **kwds):
        # begin wxGlade: AddFrame.__init__
        kwds["style"] = wx.DEFAULT_FRAME_STYLE
        wx.Frame.__init__(self, *args, **kwds)
        self.notebook_2 = wx.Notebook(self, -1, style=0)
        self.film_information = wx.Panel(self.notebook_2, -1)
        self.label_2 = wx.StaticText(self.film_information, -1, _("Type in the original film title, select source and choose\nGet from web. Griffith will try to fetch all the related\ninformation from web."), style=wx.ALIGN_CENTRE)
        self.o_title_txt = wx.StaticText(self.film_information, -1, _("Original Title"))
        self.o_title = wx.TextCtrl(self.film_information, -1, "")
        self.label_3 = wx.StaticText(self.film_information, -1, _("Title"))
        self.title = wx.TextCtrl(self.film_information, -1, "")
        self.static_line_1 = wx.StaticLine(self.film_information, -1)
        self.rating = wx.StaticText(self.film_information, -1, _("Rating"))
        self.slider_1 = wx.Slider(self.film_information, -1, 0, 0, 10, style=wx.SL_HORIZONTAL|wx.SL_AUTOTICKS)
        self.poster = wx.BitmapButton(self.film_information, -1, wx.NullBitmap)
        self.search = wx.Button(self.film_information, -1, _("Search"))
        self.fill_empty = wx.CheckBox(self.film_information, -1, _("Fill empty field only"))
        self.cancel = wx.Button(self.film_information, -1, _("Cancel"))
        self.add = wx.Button(self.film_information, -1, _("Add movie"))
        self.add_close = wx.Button(self.film_information, -1, _("Add film and close"))
        self.clear = wx.Button(self.film_information, -1, _("Clear"))
        self.details = wx.Panel(self.notebook_2, -1)

        self.__set_properties()
        self.__do_layout()
        # end wxGlade

    def __set_properties(self):
        # begin wxGlade: AddFrame.__set_properties
        self.SetTitle(_("Add a new film"))
        self.SetFocus()
        self.o_title.SetMinSize((245, -1))
        self.title.SetMinSize((300, -1))
        self.poster.SetMinSize((150, 200))
        # end wxGlade

    def __do_layout(self):
        # begin wxGlade: AddFrame.__do_layout
        sizer_7 = wx.BoxSizer(wx.HORIZONTAL)
        sizer_8 = wx.BoxSizer(wx.VERTICAL)
        sizer_10 = wx.BoxSizer(wx.HORIZONTAL)
        sizer_9 = wx.BoxSizer(wx.HORIZONTAL)
        sizer_11 = wx.BoxSizer(wx.VERTICAL)
        sizer_12 = wx.BoxSizer(wx.VERTICAL)
        sizer_15 = wx.BoxSizer(wx.HORIZONTAL)
        sizer_14 = wx.BoxSizer(wx.HORIZONTAL)
        sizer_13 = wx.BoxSizer(wx.HORIZONTAL)
        sizer_7.Add((10, 0), 0, 0, 0)
        sizer_12.Add(self.label_2, 0, wx.ALIGN_CENTER_HORIZONTAL, 0)
        sizer_12.Add((0, 20), 0, 0, 0)
        sizer_13.Add(self.o_title_txt, 0, 0, 0)
        sizer_13.Add((10, 0), 0, 0, 0)
        sizer_13.Add(self.o_title, 0, 0, 0)
        sizer_12.Add(sizer_13, 0, wx.EXPAND, 0)
        sizer_12.Add((0, 20), 0, 0, 0)
        sizer_14.Add(self.label_3, 0, 0, 0)
        sizer_14.Add((10, 0), 0, 0, 0)
        sizer_14.Add(self.title, 0, 0, 0)
        sizer_12.Add(sizer_14, 0, wx.EXPAND, 0)
        sizer_12.Add((0, 20), 0, 0, 0)
        sizer_12.Add(self.static_line_1, 0, wx.EXPAND, 0)
        sizer_12.Add((0, 20), 0, 0, 0)
        sizer_15.Add(self.rating, 0, 0, 0)
        sizer_15.Add(self.slider_1, 0, 0, 0)
        sizer_12.Add(sizer_15, 0, wx.EXPAND, 0)
        sizer_9.Add(sizer_12, 0, wx.EXPAND, 0)
        sizer_11.Add(self.poster, 0, wx.ALIGN_RIGHT, 0)
        sizer_11.Add(self.search, 0, wx.EXPAND, 0)
        sizer_11.Add(self.fill_empty, 0, wx.ALIGN_CENTER_HORIZONTAL, 0)
        sizer_11.Add((0, 10), 0, 0, 0)
        sizer_9.Add(sizer_11, 1, wx.EXPAND, 0)
        sizer_8.Add(sizer_9, 0, wx.EXPAND, 0)
        sizer_10.Add(self.cancel, 0, 0, 0)
        sizer_10.Add(self.add, 0, 0, 0)
        sizer_10.Add(self.add_close, 0, 0, 0)
        sizer_10.Add(self.clear, 0, 0, 0)
        sizer_8.Add(sizer_10, 0, wx.ALIGN_CENTER_HORIZONTAL, 0)
        sizer_8.Add((0, 10), 0, 0, 0)
        self.film_information.SetSizer(sizer_8)
        self.notebook_2.AddPage(self.film_information, _("Film information"))
        self.notebook_2.AddPage(self.details, _("Details"))
        sizer_7.Add(self.notebook_2, 1, wx.EXPAND, 0)
        sizer_7.Add((10, 0), 0, 0, 0)
        self.SetSizer(sizer_7)
        sizer_7.Fit(self)
        self.Layout()
        self.Centre()
        # end wxGlade

# end of class AddFrame