# -*- coding: utf-8 -*-
# generated by wxGlade 0.6.3 on Sat Mar 15 14:02:48 2008

import wx

# begin wxGlade: dependencies
# end wxGlade

# begin wxGlade: extracode

# end wxGlade

class ViewerFrame(wx.Frame):
    def __init__(self, *args, **kwds):
        # begin wxGlade: ViewerFrame.__init__
        kwds["style"] = wx.CAPTION|wx.CLOSE_BOX|wx.MINIMIZE_BOX|wx.MAXIMIZE_BOX|wx.STAY_ON_TOP|wx.SYSTEM_MENU|wx.RESIZE_BORDER|wx.FRAME_TOOL_WINDOW|wx.FRAME_FLOAT_ON_PARENT|wx.CLIP_CHILDREN
        wx.Frame.__init__(self, *args, **kwds)
        self.poster = wx.StaticBitmap(self, -1, wx.NullBitmap)

        self.__set_properties()
        self.__do_layout()
        # end wxGlade

    def __set_properties(self):
        # begin wxGlade: ViewerFrame.__set_properties
        self.SetTitle(_("Poster Viewer"))
        # end wxGlade

    def __do_layout(self):
        # begin wxGlade: ViewerFrame.__do_layout
        sizer_6 = wx.BoxSizer(wx.VERTICAL)
        sizer_6.Add(self.poster, 0, wx.EXPAND, 0)
        self.SetSizer(sizer_6)
        sizer_6.Fit(self)
        self.Layout()
        # end wxGlade

# end of class ViewerFrame


